language: php
php:
  - 7.1
  - 7.2
before_script:
  - pecl install -f mongodb-stable
  - composer self-update
  - composer install
script:
  - vendor/bin/phing
  - >
    wget https://github.com/maglnet/ComposerRequireChecker/releases/download/0.2.1/composer-require-checker.phar
    && php composer-require-checker.phar check composer.json
after_script:
  - php vendor/bin/coveralls -v
