language: php
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
before_script:
  - composer self-update
  - composer install
script:
  - vendor/bin/phing
after_script:
  - php vendor/bin/coveralls -v

jobs:
  include:
    - stage: test
      os: windows
      dist: 1803-containers
      language: sh # No PHP currently
      env: PHP_VERSION=7.3.12
      install:
        - choco install php --version=${PHP_VERSION} --package-parameters="/InstallDir:c:\tools\php"
        - choco install composer --ia "/DEV=C:\tools\php"
        - cp 'C:\tools\php\php.ini-production' 'C:\tools\php\php.ini'
        - echo 'memory_limit=1G' >> 'C:\tools\php\php.ini'
        - echo 'date.timezone="UTC"' >> 'C:\tools\php\php.ini'
        - echo 'extension_dir=ext' >> 'C:\tools\php\php.ini'
        - echo 'extension=php_mbstring.dll' >> 'C:\tools\php\php.ini'
        - echo 'extension=php_openssl.dll' >> 'C:\tools\php\php.ini'
        - echo 'extension=php_soap.dll' >> 'C:\tools\php\php.ini'
        - echo 'extension=php_mysqli.dll' >> 'C:\tools\php\php.ini'
        - echo 'extension=php_intl.dll' >> 'C:\tools\php\php.ini'
        - export PATH=/c/tools/php:$PATH
      script:
        - vendor/bin/phing tests
        - vendor/bin/phing phpstan
